import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';

/**
 * Async thunk to fetch logs from the WordPress REST API.
 * createAsyncThunk handles the entire async lifecycle (pending, fulfilled, rejected).
 */
export const fetchLogs = createAsyncThunk(
    'logs/fetchLogs',
    async ({ page = 1, per_page = 20 }, { rejectWithValue }) => {
        const { api_url, nonce } = window.gamify_app_data || {};
        try {
            const response = await fetch(`${api_url}logs?page=${page}&per_page=${per_page}`, {
                headers: { 'X-WP-Nonce': nonce },
            });

            if (!response.ok) {
                throw new Error('Server responded with an error!');
            }

            const data = await response.json();
            const total = response.headers.get('X-WP-Total');
            const totalPages = response.headers.get('X-WP-TotalPages');

            return { logs: data, total, totalPages };
        } catch (error) {
            return rejectWithValue(error.message);
        }
    }
);

const initialState = {
    items: [],
    status: 'idle', // 'idle' | 'loading' | 'succeeded' | 'failed'
    error: null,
    pagination: {
        total: 0,
        totalPages: 0,
        currentPage: 1,
    },
};

const logsSlice = createSlice({
    name: 'logs',
    initialState,
    reducers: {
        // Synchronous reducers can be added here if needed
    },
    // `extraReducers` handle actions generated by createAsyncThunk
    extraReducers: (builder) => {
        builder
            .addCase(fetchLogs.pending, (state) => {
                state.status = 'loading';
                state.error = null;
            })
            .addCase(fetchLogs.fulfilled, (state, action) => {
                state.status = 'succeeded';
                state.items = action.payload.logs;
                state.pagination.total = parseInt(action.payload.total, 10);
                state.pagination.totalPages = parseInt(action.payload.totalPages, 10);
            })
            .addCase(fetchLogs.rejected, (state, action) => {
                state.status = 'failed';
                state.error = action.payload;
            });
    },
});

export default logsSlice.reducer;