<?php

namespace Gamify;

// Exit if accessed directly.
if (! defined('ABSPATH')) {
    exit;
}

/**
 * Handles the enqueuing of all frontend and backend assets (CSS, JS).
 */
class Assets
{
    /**
     * Initialize the Assets class.
     * This matches the gamify structure.
     */
    public static function init()
    {
        $self = new self();
        add_action('admin_enqueue_scripts', [$self, 'enqueue_admin_assets']);

        // If you have frontend scripts later, you can add them here:
        // add_action('wp_enqueue_scripts', [$self, 'frontend_scripts']);
    }

    /**
     * Prepares the array of data to be passed to JavaScript.
     * This replicates the structure found in gamify.
     *
     * @return array
     */
    private function get_scripts_data()
    {
        return array(
            'nonce'                 => wp_create_nonce('wp_rest'),
            'gamify_nonce'          => wp_create_nonce('gamify_nonce'),
            'rest_url'              => rest_url(),
            'namespace'             => 'gamify/v1/', // Update if your API namespace differs
            'plugin_root_url'       => GAMIFY_URL,
            'plugin_root_path'      => GAMIFY_PATH,
            'ajaxurl'               => esc_url(admin_url('admin-ajax.php')),
            'site_url'              => site_url(),
            'admin_url'             => admin_url(),
            'route_path'            => wp_parse_url(admin_url(), PHP_URL_PATH),

            // Using the Helper class we created
            'menu'                  => wp_json_encode(Helper::get_admin_menu_list()),

            'is_plain_permalink'    => (bool) empty(get_option('permalink_structure')),
            'is_pro'                => true, // Set based on your plugin's logic
        );
    }

    /**
     * Filters and retrieves backend-specific script data.
     *
     * @return array
     */
    private function get_backend_scripts_data()
    {
        return apply_filters('gamify/assets/backend_scripts_data', $this->get_scripts_data());
    }

    /**
     * Enqueues scripts and styles for the admin dashboard.
     *
     * @param string $hook The current admin page hook.
     */
    public function enqueue_admin_assets($hook)
    {
        // Only load assets on our plugin's admin pages.
        if (strpos($hook, 'gamify') === false) {
            return;
        }

        // Dynamically construct the filename using the plugin version constant.
        $versioned_filename = 'backend.' . GAMIFY_VERSION;

        // Build the full path to the asset manifest file (`.asset.php`).
        $script_asset_path = GAMIFY_PATH . 'assets/build/' . $versioned_filename . '.asset.php';

        // Check if the asset file exists.
        if (! file_exists($script_asset_path)) {
            $error_message  = '<strong>Gamify Plugin Error:</strong> Build files are missing.<br>';
            $error_message .= 'Please run <strong>npm run build</strong> in the plugin\'s root directory.<br>';
            $error_message .= 'Expected asset file at: <code>' . esc_html($script_asset_path) . '</code>';
            wp_die(wp_kses_post($error_message));
            return;
        }

        // Include the asset file dependencies.
        $script_asset = require($script_asset_path);

        // Enqueue WordPress Media (Required if using Media Uploads in React)
        if (! did_action('wp_enqueue_media')) {
            wp_enqueue_media();
        }

        // Enqueue the CSS file generated by Webpack.
        $style_path = GAMIFY_PATH . 'assets/build/backend.css';
        if (file_exists($style_path)) {
            wp_enqueue_style(
                'gamify-admin-style',
                GAMIFY_URL . 'assets/build/backend.css',
                ['wp-components'],
                $script_asset['version']
            );
        }

        // Enqueue the main JavaScript file for the React application.
        wp_enqueue_script(
            'gamify-admin-script',
            GAMIFY_URL . 'assets/build/' . $versioned_filename . '.js',
            $script_asset['dependencies'],
            $script_asset['version'],
            true
        );

        // Pass data from PHP to the React app using the new structure.
        wp_localize_script(
            'gamify-admin-script',
            'GamifyGlobal', // This global variable will contain all data from get_scripts_data()
            $this->get_backend_scripts_data()
        );

        // Set script translations
        wp_set_script_translations('gamify-admin-script', 'gamify', GAMIFY_PATH . 'languages/');
    }
}
