<?php

namespace Gamify;

// Exit if accessed directly.
if (! defined('ABSPATH')) {
    exit;
}

/**
 * Handles the enqueuing of all frontend and backend assets (CSS, JS).
 */
class Assets
{
    /**
     * Constructor. Hooks into WordPress actions.
     */
    public function __construct()
    {
        add_action('admin_enqueue_scripts', [$this, 'enqueue_admin_assets']);
    }

    /**
     * Enqueues scripts and styles for the admin dashboard.
     *
     * This method dynamically locates the asset files generated by Webpack
     * using the version defined in the main plugin file.
     *
     * @param string $hook The current admin page hook.
     */
    public function enqueue_admin_assets($hook)
    {
        // Only load assets on our plugin's admin pages.
        // This checks if the page hook contains the string 'gamify'.
        if (strpos($hook, 'gamify') === false) {
            return;
        }

        // Dynamically construct the filename using the plugin version constant.
        $versioned_filename = 'backend.' . GAMIFY_VERSION;

        // Build the full path to the asset manifest file (`.asset.php`).
        $script_asset_path = GAMIFY_PATH . 'assets/build/' . $versioned_filename . '.asset.php';

        // Check if the asset file exists. If not, show a helpful error for developers.
        if (! file_exists($script_asset_path)) {
            $error_message  = '<strong>Gamify Plugin Error:</strong> Build files are missing.<br>';
            $error_message .= 'Please run <strong>npm run build</strong> in the plugin\'s root directory.<br>';
            $error_message .= 'Expected asset file at: <code>' . esc_html($script_asset_path) . '</code>';
            wp_die($error_message);
            return;
        }

        // Include the asset file, which returns an array of dependencies and a version hash.
        $script_asset = require($script_asset_path);

        // Enqueue the main JavaScript file for the React application.
        wp_enqueue_script(
            'gamify-admin-script',
            GAMIFY_URL . 'assets/build/' . $versioned_filename . '.js',
            $script_asset['dependencies'],
            $script_asset['version'], // Use the version hash from the asset file for cache busting.
            true // Load the script in the footer.
        );

        // Enqueue the CSS file generated by Webpack.
        // Check if the file exists, as Webpack might not generate it if there's no CSS.
        $style_path = GAMIFY_PATH . 'assets/build/backend.css';
        if (file_exists($style_path)) {
            wp_enqueue_style(
                'gamify-admin-style',
                GAMIFY_URL . 'assets/build/backend.css',
                ['wp-components'], // Dependency for WordPress UI components styles.
                $script_asset['version']
            );
        }

        // Pass data from PHP to our React app using wp_localize_script.
        // This creates a global JavaScript object: `gamify_app_data`.
        wp_localize_script('gamify-admin-script', 'gamify_app_data', [
            'api_url' => rest_url('gamify/v1/'),
            'nonce'   => wp_create_nonce('wp_rest'),
            'basename'  => '/wp-admin/admin.php',
            'page'      => isset($_GET['page']) ? sanitize_key($_GET['page']) : 'gamify',
        ]);
    }
}
